.SUFFIXES:

ifeq ($(strip $(DEVKITPRO)),)
$(error "Please set DEVKITPRO")
endif

ifeq ($(strip $(DEVKITARM)),)
$(error "Please set DEVKITARM")
endif

include $(DEVKITARM)/3ds_rules

TARGET   := nuclearrt-runtime
BUILD    := build_3ds
SOURCES  := source
DATA     := data
INCLUDES := include
PAK_FILE := copy/all/assets.pak
ROMFS := romfs
ICON := icon.png
PREFIX := arm-none-eabi-
CC     := $(PREFIX)gcc
CXX    := $(PREFIX)g++

ARCH := -march=armv6k -mtune=mpcore -mfloat-abi=hard -mfpu=vfp

PKG_CONFIG := $(DEVKITPRO)/portlibs/3ds/bin/arm-none-eabi-pkg-config

CFLAGS := $(ARCH) \
          $(shell $(PKG_CONFIG) --cflags sdl2 SDL2_image SDL2_ttf) \
          -Wall -Wno-unused -g3 -Og \
          -ffunction-sections -fdata-sections \
          -DPLATFORM_3DS -DNUCLEAR_BACKEND_SDL2 -D__3DS__

CXXFLAGS := $(CFLAGS) -std=c++17

LDFLAGS := $(ARCH) \
           -specs=3dsx.specs \
           -g -Wl,-Map,$(notdir $*.map) \
           -Wl,--gc-sections


LIBS := $(shell $(PKG_CONFIG) --libs sdl2 SDL2_image SDL2_ttf) \
        -lctru \
        -lm

LIBDIRS := $(PORTLIBS) $(CTRULIB)

ifneq ($(BUILD),$(notdir $(CURDIR)))

export OUTPUT := $(CURDIR)/$(TARGET)
export TOPDIR := $(CURDIR)

export VPATH := $(foreach dir,$(SOURCES),$(CURDIR)/$(dir)) \
                $(foreach dir,$(DATA),$(CURDIR)/$(dir))

export DEPSDIR := $(CURDIR)/$(BUILD)

CFILES   := $(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.c)))
CPPFILES := $(filter-out SDL3%.cpp SDL2WiiU%.cpp, $(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.cpp))))
SFILES   := $(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.s)))
BINFILES := $(foreach dir,$(DATA),$(notdir $(wildcard $(dir)/*.*)))

export LD := $(CXX)

export OFILES_BIN := $(addsuffix .o,$(BINFILES))
export OFILES_SRC := $(CPPFILES:.cpp=.o) $(CFILES:.c=.o) $(SFILES:.s=.o)
export OFILES     := $(OFILES_BIN) $(OFILES_SRC)
export HFILES_BIN := $(addsuffix .h,$(subst .,_,$(BINFILES)))

export INCLUDE := $(foreach dir,$(INCLUDES),-I$(CURDIR)/$(dir)) \
                  $(foreach dir,$(LIBDIRS),-I$(dir)/include) \
                  -I$(CURDIR)/$(BUILD)

export LIBPATHS := $(foreach dir,$(LIBDIRS),-L$(dir)/lib)
export ROMFS := $(CURDIR)/$(ROMFS)

.PHONY: all clean $(BUILD)

all: $(BUILD)

$(BUILD):
	@[ -d $@ ] || mkdir -p $@
	@$(MAKE) --no-print-directory -C $(BUILD) -f $(CURDIR)/Makefile.3ds

clean:
	@echo clean ...
	@rm -fr $(BUILD) $(TARGET).elf $(TARGET).3dsx $(TARGET).smdh $(TARGET)_package

else

.PHONY: all prepare_romfs package_dir

DEPENDS := $(addprefix $(DEPSDIR)/,$(OFILES_SRC:.o=.d))

all: prepare_romfs $(OUTPUT).3dsx package_dir

prepare_romfs:
	@mkdir -p "$(ROMFS)"
	@if [ -f "$(TOPDIR)/$(PAK_FILE)" ]; then \
		cp "$(TOPDIR)/$(PAK_FILE)" "$(ROMFS)/assets.pak"; \
	fi

$(OUTPUT).3dsx: prepare_romfs $(OUTPUT).elf $(OUTPUT).smdh
	3dsxtool "$(OUTPUT).elf" "$(OUTPUT).3dsx" --smdh="$(OUTPUT).smdh" --romfs="$(ROMFS)"

$(OUTPUT).smdh:
	smdhtool --create "NuclearRT" "NuclearRT Runtime" "shishkabob" "$(TOPDIR)/$(ICON)" "$(OUTPUT).smdh"

$(OUTPUT).elf: $(OFILES)
	$(LD) $(LDFLAGS) $(LIBPATHS) $(OFILES) $(LIBS) -o $@

$(OFILES_SRC): $(HFILES_BIN)

PACKAGE_DIR := $(OUTPUT)_package

package_dir: $(OUTPUT).3dsx
	@mkdir -p "$(PACKAGE_DIR)/3ds/nuclearrt"
	@cp "$(OUTPUT).3dsx" "$(PACKAGE_DIR)/3ds/nuclearrt/nuclearrt-runtime.3dsx"
	@if [ -f "$(OUTPUT).smdh" ]; then \
		cp "$(OUTPUT).smdh" "$(PACKAGE_DIR)/3ds/nuclearrt/nuclearrt-runtime.smdh"; \
	fi

%.bin.o %_bin.h: %.bin
	@echo $(notdir $<)
	@$(bin2o)

%.o: %.cpp
	@echo $(notdir $<)
	$(CXX) -MMD -MP -MF $(DEPSDIR)/$*.d $(CXXFLAGS) $(INCLUDE) -c $< -o $@

%.o: %.c
	@echo $(notdir $<)
	$(CC) -MMD -MP -MF $(DEPSDIR)/$*.d $(CFLAGS) $(INCLUDE) -c $< -o $@

-include $(DEPENDS)

endif