.SUFFIXES:

ifeq ($(strip $(VITASDK)),)
$(error "Please set VITASDK in your environment. export VITASDK=/usr/local/vitasdk")
endif

PKG_CONFIG := $(VITASDK)/bin/arm-vita-eabi-pkg-config

TARGET      := nuclearrt-runtime
BUILD       := build_vita
SOURCES     := source
DATA        := data
INCLUDES  := include
PAK_FILE := copy/all/assets.pak

APP_TITLE   := NuclearRT Runtime
APP_AUTHOR  := shishkabob
APP_VERSION := 1.0
TITLE_ID    := NUCL00001

PREFIX  := arm-vita-eabi-
CC      := $(PREFIX)gcc
CXX     := $(PREFIX)g++
AR      := $(PREFIX)ar
STRIP   := $(PREFIX)strip

ARCH    := -march=armv7-a -mfpu=neon -mfloat-abi=hard

CFLAGS := $(shell $(PKG_CONFIG) --cflags sdl2 SDL2_image SDL2_ttf) \
            -Wall -Wno-unused -g3 -Og -fno-omit-frame-pointer \
            -ffunction-sections \
            $(ARCH) \
            $(foreach dir,$(INCLUDES),-I$(dir))

CFLAGS  += -DPLATFORM_VITA -DNUCLEAR_BACKEND_SDL2 -D__vita__
CFLAGS += -g -O0
CXXFLAGS := $(CFLAGS) -std=c++17

LDFLAGS := -Wl,-q $(ARCH)

LIBS    := $(shell $(PKG_CONFIG) --libs sdl2 SDL2_image SDL2_ttf) \
            -lSceDisplay_stub \
            -lSceGxm_stub \
            -lSceCtrl_stub \
            -lSceAudio_stub \
            -lSceSysmodule_stub \
            -lSceCommonDialog_stub \
            -lSceAppMgr_stub \
            -lSceTouch_stub \
            -lSceHid_stub \
            -lm \
            -lpthread

#---------------------------------------------------------------------------------

ifneq ($(BUILD),$(notdir $(CURDIR)))

export OUTPUT   := $(CURDIR)/$(TARGET)
export TOPDIR   := $(CURDIR)

export VPATH    := $(foreach dir,$(SOURCES),$(CURDIR)/$(dir)) \
                   $(foreach dir,$(DATA),$(CURDIR)/$(dir))

export DEPSDIR  := $(CURDIR)/$(BUILD)

CFILES      := $(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.c)))
CPPFILES := $(filter-out SDL3%.cpp, $(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.cpp))))
SFILES      := $(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.s)))
BINFILES    := $(foreach dir,$(DATA),$(notdir $(wildcard $(dir)/*.*)))

export LD   := $(CXX)

export OFILES_BIN   := $(addsuffix .o,$(BINFILES))
export OFILES_SRC   := $(CPPFILES:.cpp=.o) $(CFILES:.c=.o) $(SFILES:.s=.o)
export OFILES       := $(OFILES_BIN) $(OFILES_SRC)
export HFILES_BIN   := $(addsuffix .h,$(subst .,_,$(BINFILES)))

export INCLUDE  := $(foreach dir,$(INCLUDES),-I$(CURDIR)/$(dir)) \
                   -I$(VITASDK)/arm-vita-eabi/include \
                   -I$(CURDIR)/$(BUILD)

export LIBPATHS := -L$(VITASDK)/arm-vita-eabi/lib

.PHONY: $(BUILD) clean all

all: $(BUILD)

$(BUILD):
	@[ -d $@ ] || mkdir -p $@
	@$(MAKE) --no-print-directory -C $(BUILD) -f $(CURDIR)/Makefile.vita

clean:
	@echo clean ...
	@rm -fr $(BUILD) $(TARGET).vpk $(TARGET).velf $(TARGET).elf eboot.bin param.sfo

#---------------------------------------------------------------------------------
else

.PHONY: all

DEPENDS := $(OFILES:.o=.d)

all: $(OUTPUT).vpk

$(OUTPUT).vpk: $(OUTPUT).velf
	vita-make-fself -s $(OUTPUT).velf eboot.bin
	vita-mksfoex -s TITLE_ID=$(TITLE_ID) "$(APP_TITLE)" param.sfo
	vita-pack-vpk -s param.sfo -b eboot.bin \
		$(if $(wildcard $(TOPDIR)/$(PAK_FILE)),-a $(TOPDIR)/$(PAK_FILE)=assets.pak) \
		$(OUTPUT).vpk

$(OUTPUT).velf: $(OUTPUT).elf
	vita-elf-create $(OUTPUT).elf $(OUTPUT).velf

$(OUTPUT).elf: $(OFILES)
	$(LD) $(LDFLAGS) $(LIBPATHS) $(OFILES) $(LIBS) -o $@

$(OFILES_SRC): $(HFILES_BIN)

%.bin.o %_bin.h: %.bin
	@echo $(notdir $<)
	@$(bin2o)

%.o: %.cpp
	@echo $(notdir $<)
	$(CXX) -MMD -MP -MF $(DEPSDIR)/$*.d $(CXXFLAGS) $(INCLUDE) -c $< -o $@

%.o: %.c
	@echo $(notdir $<)
	$(CC) -MMD -MP -MF $(DEPSDIR)/$*.d $(CFLAGS) $(INCLUDE) -c $< -o $@

-include $(DEPENDS)

endif